name: TP-GWAS
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - nodejs
  - libgomp
  - r-irkernel
  - r-base=4
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
  - plink=1.90b6.18-0
  - king=2.2.4
  - r-qqman==0.1.4
